### ISSUE TITLE
Delete plugin

### ISSUE THREAD

**Issue by dalmeraz** [gjjuarez/Team01_BEAT#3]
Similar to how we delete projects, we must delete plugin. The parameters it should take are the Plugin Name.

**Comment by Alexander-Wieczkowski** [comment]
It already existed. It was named 'delete_plugin_given_name(name)'. I added a try/catch for added error catching and to match the delete plugin methods structure.

**Comment by gjjuarez** [comment]
Verify that deleting a plugin actually works. On the gui it will disappear but it prints out an error message in the terminal

**Comment by Alexander-Wieczkowski** [comment]
Fixed a wrong data type bug in UiMain that prevented the delete_plugin_given_name(name) method from executing.
